### ISSUE TITLE
drupal_7_entity database whereas I'm not using it

### ISSUE THREAD

**Issue by eurecomphil** [evolvingweb/migrate_example_i18n#2]
Hi,

Thank you for your work.
I'm trying to migrate a D6 FR/EN website to D8.
I'm following your process Migrate hybrids (D6 content translations to D8) and I have some issues. 
When I try to do migrate-import of example_hybrid_base (by the way, I guess there is typo error in "Hybrid base migration" section inside the Drush command line. I guess it is "example_hybrid_base" instead of "example_hybrid_i18n") it is complaining about "drupal_7_entity".

`drush migrate-import example_hybrid_base --update`
`exception 'Drupal\Core\Database\ConnectionNotDefinedException' with message 'The specified database connection is not defined: drupal_7_entity' in `

Where as in my settings I have only : 
`$databases['default']['default'] = array (`
and
`$databases['drupal_6']['default'] = array (`

Any clue ?

Thanks a lot in advance !

**Comment by jigarius** [comment]
You need to install the database dumps provided in the example and define
those connections the settings file. What the error means is that the
database couldn't be found.

**Comment by eurecomphil** [comment]
Since I'm migrating only stuff from my D6 to D8, I kept only the following files as a good base to start :

- config/install/migrate_plus.migration_group.example_hybrid.yml
- config/install/migrate_plus.migration.example_hybrid_base.yml
- config/install/migrate_plus.migration.example_hybrid_i18n.yml
- migrate_example_i18n.module
- migrate_example_i18n.install
- migrate_example_i18n.info.install

I can confirm that with this custom module, I'm easily able to copy all my D6 pages and articles with their translations to my new D8 ! Thank you again for sharing your work.

root@xxxxxxx: vendor/bin/drush migrate-import --group=example_hybrid
Processed 150 items (150 created, 0 updated, 0 failed, 0 ignored) - done with 'example_hybrid_base'                   [status]
Processed 120 items (120 created, 0 updated, 0 failed, 0 ignored) - done with 'example_hybrid_i18n'                   [status]
